In [94]:
% Ширина: 112
% Длинна: 610
% До крепления: 101
% Креплений: 13
% Расстяние между креплениями: 47
% От стены до крепления слева: 10
% От стены до крепления справа: 6
% Провод слева: 330
% Провод справа: 270

1.12*6.10/0.81
8*9/11
11*224
ans*7

ans =  8.4346
ans =  6.5455
ans =  2464
ans =  17248


In [164]:
function [Sz, Sx] = stack_transform_matricies(nz, nx)
    Sz = shift(diag(ones(nz,1),nz+nx,nz), 0,dim=1);
    Sx = shift(diag(ones(nx,1),nz+nx,nx),nz,dim=1);
end

x = [1;2]
z = [3;4;5]

[Sz, Sx] = stack_transform_matricies(rows(z),rows(x))

zx = Sz*z + Sx*x

x =

   1
   2

z =

   3
   4
   5

Sz =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1
   0   0   0
   0   0   0

Sx =

   0   0
   0   0
   0   0
   1   0
   0   1

zx =

   3
   4
   5
   1
   2



In [194]:
Z = rand(2,4)
z = Z(:,1)
ZZ = Z*Z'
zz = z*z'
[z z]*[z z]'/2
dot(z,z')

Z =

   0.079567   0.265220   0.247364   0.996793
   0.641660   0.106984   0.219862   0.820672

z =

   0.079567
   0.641660

ZZ =

   1.13146   0.95186
   0.95186   1.14502

zz =

   0.0063309   0.0510550
   0.0510550   0.4117278

ans =

   0.0063309   0.0510550
   0.0510550   0.4117278

ans =  0.41806


In [195]:
function x = test_weigted_avg(k, n)
    x = (1-k)^n;
    for i = 1:n
        x += k*(1-k)^(n-i);
    end
end

k = 0.5
for n = 1:100
    n
    test_weigted_avg(k,n)    
end

k =  0.50000
n =  1
ans =  1
n =  2
ans =  1
n =  3
ans =  1
n =  4
ans =  1
n =  5
ans =  1
n =  6
ans =  1
n =  7
ans =  1
n =  8
ans =  1
n =  9
ans =  1
n =  10
ans =  1
n =  11
ans =  1
n =  12
ans =  1
n =  13
ans =  1
n =  14
ans =  1
n =  15
ans =  1
n =  16
ans =  1
n =  17
ans =  1
n =  18
ans =  1
n =  19
ans =  1
n =  20
ans =  1
n =  21
ans =  1
n =  22
ans =  1
n =  23
ans =  1
n =  24
ans =  1
n =  25
ans =  1
n =  26
ans =  1
n =  27
ans =  1
n =  28
ans =  1
n =  29
ans =  1
n =  30
ans =  1
n =  31
ans =  1
n =  32
ans =  1
n =  33
ans =  1
n =  34
ans =  1
n =  35
ans =  1
n =  36
ans =  1
n =  37
ans =  1
n =  38
ans =  1
n =  39
ans =  1
n =  40
ans =  1
n =  41
ans =  1
n =  42
ans =  1
n =  43
ans =  1
n =  44
ans =  1
n =  45
ans =  1
n =  46
ans =  1
n =  47
ans =  1
n =  48
ans =  1
n =  49
ans =  1
n =  50
ans =  1
n =  51
ans =  1
n =  52
ans =  1
n =  53
ans =  1
n =  54
ans =  1
n =  55
ans =  1
n =  56
ans =  1
n =  57
ans =  1
n =  58
ans =  1
n =  59
an

In [9]:
nchoosek(40,2) / nchoosek(50,2)
40/50 * 39/49

ans =  0.63673
ans =  0.63673


In [19]:
source('clearest-nn.m');
x.a = 'a'
y.a = 'b'
y.b = 'b'
xy = mergereplace(y,x)

ans = THE CLEAREST NEURAL NETWORK FRAMEWORK BY UNDWAD
x =

  scalar structure containing the fields:

    a = a

y =

  scalar structure containing the fields:

    b = b
    a = b

y =

  scalar structure containing the fields:

    b = b
    a = b

xy =

  scalar structure containing the fields:

    b = b
    a = a



In [28]:
M = [0.387850845167067, -1.91708509693545, 1.03741974556384, 0, 2.07531524296433, 0.0024641140141802, -0.771326030895215, 0, 0.666724560592778, 1.10754771216624, 1.79741472706002, 0, 2447740.89311184, 2940177.65302832, 5086429.55978499, 1 ]
M = reshape(M, 4, 4)
x = [ -7.16989613, -0.776942790, 0, 1 ]
% { 2447736.50, 2940191.50, 5086422.50, 1.00000000 }
x'
M*x'

M =

 Columns 1 through 6:

   3.8785e-01  -1.9171e+00   1.0374e+00   0.0000e+00   2.0753e+00   2.4641e-03

 Columns 7 through 12:

  -7.7133e-01   0.0000e+00   6.6672e-01   1.1075e+00   1.7974e+00   0.0000e+00

 Columns 13 through 16:

   2.4477e+06   2.9402e+06   5.0864e+06   1.0000e+00

M =

   3.8785e-01   2.0753e+00   6.6672e-01   2.4477e+06
  -1.9171e+00   2.4641e-03   1.1075e+00   2.9402e+06
   1.0374e+00  -7.7133e-01   1.7974e+00   5.0864e+06
   0.0000e+00   0.0000e+00   0.0000e+00   1.0000e+00

x =

  -7.16990  -0.77694   0.00000   1.00000

ans =

  -7.16990
  -0.77694
   0.00000
   1.00000

ans =

   2.4477e+06
   2.9402e+06
   5.0864e+06
   1.0000e+00



ctx =

  scalar structure containing the fields:

    a = A

ctx =

  scalar structure containing the fields:

    a = A

ctx_b =  100


In [43]:
wages = 158700
overwork = 75823
total = wages + overwork
percent = total / 100
diff = 30198

diff /= percent

recv = 138369 + 65956
recv /= percent

wages =  158700
overwork =  75823
total =  234523
percent =  2345.2
diff =  30198
diff =  12.876
recv =  204325
recv =  87.124


In [48]:
x = [1 1 1 1 1; 2 2 2 2 2; 3 3 3 3 3]
y = [ 0 0 0 11 0; 0 0 22 0 0; 0 33 0 0 0 ]
x .* (y == 0) .+ y

x =

   1   1   1   1   1
   2   2   2   2   2
   3   3   3   3   3

y =

    0    0    0   11    0
    0    0   22    0    0
    0   33    0    0    0

ans =

    1    1    1   11    1
    2    2   22    2    2
    3   33    3    3    3



In [97]:
source('clearest-nn.m');
x = setsome(zeros(3,5), rand(3,2), :, 3:4)
x = setsome(zeros(9,1), rand(3,1), [2,4,6])

ans = THE CLEAREST NEURAL NETWORK FRAMEWORK BY UNDWAD
x =

   0.00000   0.00000   0.11500   0.49164   0.00000
   0.00000   0.00000   0.24550   0.85471   0.00000
   0.00000   0.00000   0.44453   0.19385   0.00000

x =

   0.00000
   0.56210
   0.00000
   0.05561
   0.00000
   0.90128
   0.00000
   0.00000
   0.00000



error: 'setsome' undefined near line 1 column 5
